version: "3.8"
services:
  nginx:
    restart: unless-stopped
    image: nginx:1-alpine
    env_file:
      - ".env"
    ports:
      - ${NGINX_DEFAULT_PORT}:80
    volumes:
      - ./project/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    
